### PR TITLE
Add support for OMS_PATH that bypasses npx

### PR DESCRIPTION
**Pull request by StoryscriptHuman**
Currently the test runner makes use of `npx`, which means it'll always use the npm-published version, which does not let us test this on everyday builds of CI since it'll only test against the published version

This PR adds support for `OMS_PATH` so test runner can specify it's own OMS path that bypasses `npx`

Sibling PR: https://github.com/microservices/node-events/pull/6

### CODE REVIEW

**Comment by StoryscriptHuman** [comment]
`oms` is not always installed globally while testing this, that's what `npx` did.

> You are reinventing PATH here

You are partially correct, we could append `oms` to path and then chunk it out and check each chunk if `oms` exists in there, and then decide whether to invoke `npx` or run `oms` directly. This approach is much more simple with less moving parts and it's been proven to work in https://circleci.com/gh/microservices/oms/2871

**Comment by wilzbach** [comment]
No that's not how `PATH` works nor is intended to work. We just need to install `oms` (or add to it).
That's just a `-g` in this case.

> This approach is much more simple 

No, it's not. You're reinventing what an OS is really good at.

**Comment by StoryscriptHuman** [comment]
The problem isn't finding `oms`, the problem is deciding whether to use `npx oms` or `oms` directly.

> No, it's not. You're reinventing what an OS is really good at.

We may be misunderstanding the problem here. I would greatly appreciate if you would open a PR to demonstrate what you mean, in the meanwhile this fixes the CI build for OMS repo.

**Comment by wilzbach** [comment]
> We may be misunderstanding the problem here. I would greatly appreciate if you would open a PR to demonstrate what you mean, in the meanwhile this fixes the CI build for OMS repo.

https://github.com/microservices/python-events/pull/10

**Pull request merged**
